# config.yaml for YOLOv8 training
# YOLOv8 Training Configuration File

# 训练的类别数目（根据数据集的实际类别数目进行修改）
nc: 6  # 6 类别，分别是 dent, scratch, crack, glass shatter, lamp broken, tire flat

# 训练集和验证集图像路径
train: /kaggle/working/car/images/train
val: /kaggle/working/car/images/val

# 预训练模型路径
# 如果你要使用YOLOv8的预训练模型，可以指定相应的路径
# 如果你用的是yolo11，可以修改为对应的权重路径
# 这里假设你已经下载了YOLOv8预训练模型
weights: /path/to/yolo11_pretrained_weights.pt

# 数据集类别标签（根据数据集的类别名称）
names:
  0: dent
  1: scratch
  2: crack
  3: glass shatter
  4: lamp broken
  5: tire flat

# 网络参数设置
# 你可以根据自己的硬件和训练需求调整这些设置
imgsz: 640  # 图像尺寸
batch_size: 16  # 每批次训练样本数
epochs: 50  # 训练的轮数
device: 0  # 使用的设备，0表示使用第一张GPU，如果没有GPU可以使用-1表示CPU
optimizer: SGD  # 优化器，可以选择SGD或者Adam
lr0: 0.01  # 初始学习率
lrf: 0.2  # 学习率的范围
momentum: 0.937  # 动量
weight_decay: 0.0005  # 权重衰减
warmup_epochs: 3  # 预热轮数
